Practical-7
desaianiruddh/User-List pull request #1
Opened 2022-04-04 11:38 UTC by desaianiruddh

2022-04-06 06:43 UTC, Rutvi25 approved these changes

2022-04-06 06:48 UTC, harshpatel-javascript approved these changes

2022-04-08 03:51 UTC, sheth-jay requested changes

2022-04-08 03:51 UTC, sheth-jay commented on package.json
> +    "prod": "env-cmd -f .env.staging npm run build"
it should be build:prod.

2022-04-08 04:30 UTC, sheth-jay approved these changes

2022-04-08 04:30 UTC, merged